from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

LAST_ACTION = {}

# =========================
# DEVICE REGISTRY
# =========================
DEVICES = {
    "light_1": {
        "device_id": "light_1",
        "device_type": "Light",
        "room": "living_room"
    },
    "fan_1": {
        "device_id": "fan_1",
        "device_type": "Fan",
        "room": "bedroom"
    },
    "ac_1": {
        "device_id": "ac_1",
        "device_type": "AC",
        "room": "living_room"
    }
}


# =========================
# INPUT MODELS
# =========================
class VoiceInput(BaseModel):
    text: str


class DecideInput(BaseModel):
    user_command: str


# 🔹 NEW: model-to-model input
class ActionInput(BaseModel):
    command: str


# =========================
# APP SETUP
# =========================
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =========================
# HELPER
# =========================
def make_action(device_key, action, value=None):
    device = DEVICES[device_key]
    return {
        "device_id": device["device_id"],
        "device_type": device["device_type"],
        "room": device["room"],
        "action": action,
        "value": value
    }


# =========================
# NLP DECISION LOGIC
# =========================
def decide_from_command(user_command: str):
    command = user_command.lower()
    actions = []

    # 🔥 AC logic
    if "hot" in command or "warm" in command:
        actions.append(make_action("ac_1", "ON"))

    if "cold" in command or "chilly" in command:
        actions.append(make_action("ac_1", "OFF"))

    if "save energy" in command or "reduce power" in command:
        actions.append(make_action("ac_1", "INCREASE_TEMPERATURE", value=2))

    # 🌀 Fan logic
    if "fan" in command and ("on" in command or "start" in command):
        actions.append(make_action("fan_1", "ON"))

    if "fan" in command and ("off" in command or "stop" in command):
        actions.append(make_action("fan_1", "OFF"))

    # 💡 Light logic
    if "light" in command and ("on" in command or "switch on" in command):
        actions.append(make_action("light_1", "ON"))

    if "light" in command and ("off" in command or "switch off" in command):
        actions.append(make_action("light_1", "OFF"))

    if not actions:
        return {
            "actions": [],
            "message": "No matching action"
        }

    return {
        "actions": actions
    }


# =========================
# ENDPOINTS
# =========================
@app.post("/decide")
async def decide(data: DecideInput):
    return decide_from_command(data.user_command)


@app.post("/voice-decide")
async def voice_decide(data: VoiceInput):
    return decide_from_command(data.text)


# 🔹 NEW: endpoint for another model / service
@app.post("/actions")
async def actions_endpoint(data: ActionInput):
    global LAST_ACTION
    LAST_ACTION = decide_from_command(data.command)
    return LAST_ACTION

@app.get("/last-actions")
async def last_actions():
    """
    Returns the most recent action generated by mic UI or any caller.
    """
    return LAST_ACTION

